// <auto-generated />
namespace Sono_Viso.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cliente_6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cliente_6));
        
        string IMigrationMetadata.Id
        {
            get { return "201607091126163_Cliente_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
